# Generated by Django 2.2.5 on 2020-06-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rests', '0002_auto_20200603_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('bus_capacity', models.IntegerField(blank=True, null=True)),
                ('bus_status', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_current_passanger', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_img', models.ImageField(blank=True, null=True, upload_to='media/img')),
            ],
        ),
        migrations.CreateModel(
            name='faire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faire_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_starting', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('place_end', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('place_time_reach', models.TimeField(blank=True, null=True)),
                ('place_time_arrival', models.TimeField(blank=True, null=True)),
                ('Bus_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_no', models.IntegerField(blank=True, null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.location')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('conductor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_no', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('conductor_image', models.ImageField(blank=True, null=True, upload_to='media/img')),
                ('Bus_no', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.faire'),
        ),
        migrations.CreateModel(
            name='booking1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('passanger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_starting', models.CharField(blank=True, max_length=100, null=True)),
                ('place_end', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('Bus_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.Bus')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rests.name')),
            ],
        ),
    ]
